name: build

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      ksp-zip-url: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip
    secrets:
      ksp-zip-password: ${{ secrets.KSP_ZIP_PASSWORD }}
